version: '3'
volumes:
  data:
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mahadev
      MARIADB_DATABASE: devdb
      MARIADB_USER: user
      MARIADB_PASSWORD: mahadev
    volumes:
      - data:/var/lib/db/mariadb
    ports:
      - "3306:3306"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mahadev
    volumes:
      - data:/var/lib/db/mongodb
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: mahadev
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mahadev
      ME_CONFIG_MONGODB_URL: mongodb://root:mahadev@mongo:27017/